### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [magwyz/pastec#1]
I find that include guards like "[HIT_H](https://github.com/Visu4link/pastec/blob/7c4c4f81e8f7432b5859a93ec953c182ed0885b0/include/hit.h#L22)" and "[INDEX_H](https://github.com/Visu4link/pastec/blob/7c4c4f81e8f7432b5859a93ec953c182ed0885b0/include/index.h#L22)" are too short for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by magwyz** [comment]
Fixed by e4e3de8b860655ba17e0d419b8f38a50600207ad.

Thanks for reporting.

**Comment by elfring** [comment]
Thanks for [your addition of a prefix](https://github.com/Visu4link/pastec/commit/12cd90659d32039dc9961280db2373738e383f03) to the include guards.
