### ISSUE TITLE
How can I add https or/and basic auth ?

### ISSUE THREAD

**Issue by florindumitru** [magwyz/pastec#15]
How can I add https or/and basic auth ?

**Comment by magwyz** [comment]
Look at the microhttpd doc:
http://www.gnu.org/software/libmicrohttpd/tutorial.html#Supporting-basic-authentication

**Comment by magwyz** [comment]
For HTTPS the following link should give you some insights:
http://www.gnu.org/software/libmicrohttpd/tutorial.html#Adding-a-layer-of-security
