### ISSUE TITLE
Compilation error : no matching function for call to ‘cv::ORB::ORB(int, double, int)’

### ISSUE THREAD

**Issue by oetienne** [magwyz/pastec#16]
Following the step by step setup instruction it fails to compile with the following error :

pastec/src/orb/orbfeatureextractor.cpp:53:24: error: no matching function for call to ‘cv::ORB::ORB(int, double, int)’

I compiled on debian wheezy.

**Comment by magwyz** [comment]
You are using a too old version of OpenCV.
