### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by axman3322** [magwyz/pastec#17]
Hi there,

We're playing around with pastec at a hackathon and we're having issues installing it. At the cmake stage, we get the error:

CMake Error at CMakeLists.txt:38 (find_package):
  By not providing "Findmicrohttpd.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "microhttpd", but CMake did not find one.

  Could not find a package configuration file provided by "microhttpd" with
  any of the following names:

```
microhttpdConfig.cmake
microhttpd-config.cmake
```

  Add the installation prefix of "microhttpd" to CMAKE_PREFIX_PATH or set
  "microhttpd_DIR" to a directory containing one of the above files.  If
  "microhttpd" provides a separate development package or SDK, be sure it has
  been installed.

These packages should be default. Any ideas?

**Comment by axman3322** [comment]
FYI don't use the latest hash. It seems if you use an earlier version, everything works.

**Comment by magwyz** [comment]
I do not think there is a compilation problem with the latest hash.

**Comment by harishannam** [comment]
having the exact same issue

**Comment by magwyz** [comment]
What distribution are you using?
