### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by Droppix** [magwyz/pastec#19]
Hi,

As this is a next release will be available? ("Next Pastec releases will contain tools that will allow you to generate your own list of visual words").

Thanks

**Comment by magwyz** [comment]
It is not planned yet. You can however contact me by email if you want the tool to generate your own list of visual words.

Best regards,

**Comment by Droppix** [comment]
Hi Adrien,

Yes, I'm interested by your tool. Can you send me, please ?

Thanks
Robert

2015-09-11 22:55 GMT+02:00 Adrien Maglo notifications@github.com:
