### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [magwyz/pastec#2]
Would you like to [replace any double quotes](https://github.com/Visu4link/pastec/blob/504bb2b04ddf75d82df6a57303258c646a64ea9a/include/imagereranker.h#L34) by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename)?

**Comment by magwyz** [comment]
Done in 058c238c9fa4fbb4a17ad0ef8a1d2d8a7f196ee4.

Thanks for reporting!

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/Visu4link/pastec/commit/2187deaa96f1812add5388f3cd02e89addfa6e01).
