### ISSUE TITLE
Standalone algorithm to make signature

### ISSUE THREAD

**Issue by jibay** [magwyz/pastec#22]
Hello,

Thanks for this great project. I would like to know if this is possible to isolate the algorithm responsible for creating the signature/fingerprint for image search query. For example, we have a mobile application and we would like to send only the signature (the signature should be computed with mobile application) to the pastec server in order to have very fast answer.

**Comment by magwyz** [comment]
Yes, it is theoretically possible but it is not on my TODO list.
