### ISSUE TITLE
Using the same Pastec instance in dev, test, prod

### ISSUE THREAD

**Issue by abournier** [magwyz/pastec#27]
It could be very interesting if we could use the same install of Pastec for different environments such development, test, production.
Ideally, an option could be given when launching Pastec -d, -t, -p (with a default to -p), and of course the creation of 3 different indexes backwardIndex-dev.dat, backwardIndex-test.dat, backwardIndex-prod.dat

Of course I can install Pastec on a small VPS for tests/dev purposes...but this option looks more practical ?

**Comment by magwyz** [comment]
There is now the "multi-indexes" branch that kind of achieve this.
It is however still experimental and there is no documentation.
