### ISSUE TITLE
Saving the index

### ISSUE THREAD

**Issue by tinusg** [magwyz/pastec#29]
From the website:

"Next Pastec releases will contain tools that will allow you to generate your own list of visual words."

From the documentation:

"This call saves the index data in a specified path."

Before I install to give it a try I would like to know if it's possible to save the index once you've built it?

**Comment by chrishein** [comment]
Yes, it is possible. That is what is meant by:
"This call saves the index data in a specified path."

Generating you own list of visual words is not related to that.
