### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [magwyz/pastec#4]
The function "[pthread_cond_signal](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_signal.html)" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/cplusplus/SIG30-CPP.+Call+only+asynchronous-safe+functions+within+signal+handlers).
I guess that a different program design will be needed for your function "[intHandler](https://github.com/Visu4link/pastec/blob/5d00b78d7bb22fee1f345999d1184e08ccf07b2c/src/main.cpp#L36)".

**Comment by magwyz** [comment]
This should be fixed by acab16c012eff9f938317b442140376b331b457d.

Thanks for reporting!

**Comment by elfring** [comment]
Are further checks and considerations needed for the implementation detail that [the member function "HTTPServer::stop" is called over a pointer](https://github.com/Visu4link/pastec/blob/058c238c9fa4fbb4a17ad0ef8a1d2d8a7f196ee4/src/main.cpp#L38) which is stored in the global variable "s"?
Is this another concern for software portability around signal handlers?
