### ISSUE TITLE
IMAGE_NOT_DECODED

### ISSUE THREAD

**Issue by Victorgf87** [magwyz/pastec#40]
Hello, I have installed pastec server on my server, and now I'm trying to make a post to add photos...
When I do  curl -X PUT --data-binary <image> <address> I keep getting the "IMAGE_.NOT_DECODED" in the json response. 
I have tried converting jpg to base64 and use the jpg file (they say jpegs are binary :S) but keep getting that error...
I would appreciate any help you would provide me. Thank you for everything :)

**Comment by magwyz** [comment]
Please provide the full curl command you are using.

**Comment by Victorgf87** [comment]
Sure.

`curl -X PUT --data-binary ./images/h3.jpg http://37.139.11.71:4212/index/images/1`

And the response: {"image_id":1,"type":"IMAGE_NOT_DECODED"}

**Comment by magwyz** [comment]
Replace "./images/h3.jpg" by "@images/h3.jpg"
The @ is important. It's the curl syntax.

**Comment by Victorgf87** [comment]
Thank you so much, I didn't see that ^^'

Now I can upload images, but if the image is bad, it says:
`pastec: jax_cm.c:845: jas_cmshapmat_apply:Assertion 0 failed. Aborted`

And the process dies
I hope you find that useful

Thanks again :)

**Comment by magwyz** [comment]
Could you attach a sample image to this issue?
Thanks

**Comment by Victorgf87** [comment]
If you are asking for the image I was using it was this file:
![h2](https://cloud.githubusercontent.com/assets/4776972/15714747/11464b68-281c-11e6-8df6-5da5d3e8ea1a.jpg)

As you can see it's just a bad image, it was a jpg file processed with base64

One last question, I'm trying to create an Android application using pastec and Retrofit, but I can't make it work. Do you know what is the exact equivalent to "--data-binary" in Retrofit? I have tried a several things like multipart with Requestbody and yet it doesn't work

Again, thanks for everything
