### ISSUE TITLE
Allowing to larget image_id values with uint64.

### ISSUE THREAD

**Issue by erogol** [magwyz/pastec#47]
Don't you think it is better to use larger values for image_id. I like to ought this change but what parts of the code depended to that change? Any help would be great.

**Comment by bperel** [comment]
The structure of the image identifier seems to be defined in [include/searcher.h](https://github.com/Visu4link/pastec/blob/dist-ver/include/searcher.h#L36). I would suggest to change it there and apply the type change where needed, for instance [src/orb/orbindex.cpp](https://github.com/Visu4link/pastec/blob/dist-ver/src/orb/orbindex.cpp#L69)

**Comment by magwyz** [comment]
Be also aware that this size influences the size of the index in the RAM and on the disk.
If I remember well, the loader and the writer must also be modified.
