### ISSUE TITLE
Setting up & compiling against non App based.

### ISSUE THREAD

**Issue by ceased-ebc** [magwyz/pastec#48]
Hi there, love the look of this, (you should set up a donation page). 

Wanting to use the own server version, though a couple of questions that do not appear to be in any readme. 

:- Images (Mentions 4x,xxx images though not in the source (git hub) so do we have to source our own and where do we store the.

:- Disple mentioned, no mention on both on how to put together both (note it's for android we will based in the cloud). https://github.com/Visu4link/displee

:- How/where data feeds, feed from our DB's (as strings of urls or actual images) into the module and return the data to our DB against the images.

:- Any constraints (i.e we will likely be completing 1-10m images a day)?

Many thanks

**Comment by magwyz** [comment]
- Pastec does not come with any image database.
- Displee is no longer available. Its backend, which was connected to Pastec, was never released in open source.
- You have to do your own benchmark depending on your constraints.
