### ISSUE TITLE
Protect against spurious wakeups

### ISSUE THREAD

**Issue by elfring** [magwyz/pastec#5]
I have seen that [no loop is used around a call](https://github.com/Visu4link/pastec/blob/5d00b78d7bb22fee1f345999d1184e08ccf07b2c/src/httpserver.cpp#L55) of the function "[pthread_cond_wait](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html)".
Would you like to reuse anything from my message on the topic "[spurious wakeup](http://groups.google.de/group/comp.programming.threads/msg/bb8299804652fdd7)"?

**Comment by magwyz** [comment]
Since acab16c012eff9f938317b442140376b331b457d, pthread_cond_wait() is no longer used.

Thanks for reporting!
