### ISSUE TITLE
License for pastec

### ISSUE THREAD

**Issue by jvanzyl** [magwyz/pastec#53]
Hi, I see a copy of the GPL and LGPL license in the source repository. I also see LGPL in the headers of the source. What is the official license for Pastec?

Thanks,

Jason

**Comment by magwyz** [comment]
The licence of Pastec is the LGPL.
According to the GNU website: https://www.gnu.org/licenses/gpl-howto.html
"All programs, whether they are released under the GPL or LGPL, should include the text version of the GPL."
