### ISSUE TITLE
Unix socket support

### ISSUE THREAD

**Issue by vmonteco** [magwyz/pastec#57]
Is there a support for unix sockets?

If yes, how to enable it? Using `./pastec -p unix:///tmp/pastec.sock visualWordsORB.dat` doesn't seem to work, nor using `unix:/tmp/pastec.sock`.

If no, would it be possible to add it?

**Comment by magwyz** [comment]
There is no support for Unix socket. This should be implementable but I am not sure I want to support that in my version.
