### ISSUE TITLE
Pastec Server Not retruns More than 100 records

### ISSUE THREAD

**Issue by kanakarajubayana** [magwyz/pastec#58]
Hi Guys,

   Can you help me I have Inserted more than 500 records into the Pastec Server 

  While I'm trying to retrieve the records Matching with the Image as mentioned below Command. I'm getting only 100 records.  

  curl -X POST --data-binary @/home/test/img/request.jpg http://localhost:4212/index/searcher

Can you please guide/help me How can I retrieve more than 100 images

Thanks
Raju

**Comment by ecdeveloper** [comment]
https://github.com/magwyz/pastec/blob/dist-ver/src/orb/orbsearcher.cpp#L287 - its hardcoded to only 100 results. If you want more - you may need to tweak the orbsearcher.
