### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [magwyz/pastec#6]
Would you like to wrap any pointer data members with the template class "[std::unique_ptr](http://en.wikipedia.org/wiki/Smart_pointer#unique_ptr)"?

Update candidates:
- [HTTPServer](https://github.com/Visu4link/pastec/blob/5d00b78d7bb22fee1f345999d1184e08ccf07b2c/src/httpserver.cpp#L36)
- [main](https://github.com/Visu4link/pastec/blob/36b13060f6f9a5e1e328fa1423367226f2e75e3c/src/main.cpp#L49)
- [ORBWordIndex](https://github.com/Visu4link/pastec/blob/5d00b78d7bb22fee1f345999d1184e08ccf07b2c/src/orb/orbwordindex.cpp#L28)

**Comment by magwyz** [comment]
Won't fix

**Comment by elfring** [comment]
Do you really prefer to keep [a broken software implementation](https://github.com/Visu4link/pastec/blob/4b6bf7c963760e562d159d801fb4aa3df46e0600/src/orb/orbwordindex.cpp#L28) (instead of [improving its robustness](http://www.drdobbs.com/cpp/the-new-csmarter-pointers/184403837))?

**Comment by magwyz** [comment]
Could you elaborate on why this code is broken?

Thank you

**Comment by elfring** [comment]
- With which pointer values will [the delete operators](http://ootips.org/yonat/4dev/smart-pointers.html#WhyBugs) be eventually called in the ORBWordIndex destructor for example if one of the previous new operator calls would throw the exception “std::bad_alloc”?
- Do you care for complete clean-up of involved system resources?
