### ISSUE TITLE
IMAGE_NOT_ENCODED

### ISSUE THREAD

**Issue by JasonG7020** [magwyz/pastec#61]
I would appreciate any help you would provide me. Thank you for everything :)

Hello, I have installed the Pastec Server on my Server, now I'm trying to use the post photos onto it but I keep getting the  {"image_id":1,"type":"IMAGE_NOT_DECODED"} as a response.

This is the curl command I am using:

    curl -X PUT --data-raw -F @/currency/imageOne.jpg http://localhost:4212/index/images/1

Any help you could give I would greatly appreciate. Thank You

**Comment by magwyz** [comment]
I really doubt that "/currency/imageOne.jpg" is the path of your image.
Please also check the parameters of your curl command line. They are not the ones given in the documentation examples.

**Comment by JasonG7020** [comment]
Sorry that was one i was changing around to see if it would work.

Here is the proper one:
     curl -X PUT --data-binary @/usr/local/bin/currency/imageOne.jpg http://localhost:4212/index/images/1

**Comment by magwyz** [comment]
Are your sure you are storing your images in "/usr/local/bin"?
This is really weird.

**Comment by JasonG7020** [comment]
Yeah the photos are stored in the currency folder there, is there something I need to do to the jpeg photos in order for it to work?
