### ISSUE TITLE
How does image resolution impact results?

### ISSUE THREAD

**Issue by ecdeveloper** [magwyz/pastec#64]
I was wondering, by indexing images with larger resolution - does is mean there are higher chances that the searcher will find a match?

Also, is there a "recommended" resolution for indexed images? 

Thanks in advance.

**Comment by abournier** [comment]
I don't think it is necessary to set a size > to 1000px.
You can test and observe the number of features extracted between a 150x150pxl, 500x500px and 1000x1000px. There will not be a huge difference, but it can depends from the kind of images.
From my side, I will send them in 600x600px.

**Comment by ecdeveloper** [comment]
Thanks for a quick reply. I was also wondering about the numeric results (features?) I'm getting. What are those numbers actually mean? Any docs I can read in this regard? 

Thanks!

**Comment by abournier** [comment]
More the image owns details and contrasts, and more the engine will extract features (vectors ?)... and more there will a possibility to find a positive in the index later.
You  can have a look there: https://arxiv.org/pdf/1710.02726.pdf

**Comment by ecdeveloper** [comment]
Thank you!
