### ISSUE TITLE
Python wrapper

### ISSUE THREAD

**Issue by DonaldTsang** [magwyz/pastec#68]
- [ ] Python wrapper (no networking restrictions) for accessing pastec
- [ ] Database can handle millions of images, and the XORing (or image comparing) of images can be easily paralleled using multi-processing or multi-threading in Python
- [ ] Standard documentations for using the wrapper

Goal: to be applied in in https://github.com/hydrusnetwork/hydrus

**Comment by magwyz** [comment]
Did you have a look at the source code ?
There is "python" directory in the main folder that contains the a python API. It is however indeed undocumented.

**Comment by DonaldTsang** [comment]
@magwyz I did, but I would like to see a Python wrapper that does not require URL API calls or servers, i.e. Having Pastec called directly from the database and image fingerprinter on the same system.

**Comment by magwyz** [comment]
Ok, understood.
I however prefer to stick for now to a pure HTTP API.

**Comment by DonaldTsang** [comment]
@magwyz That could be a future feature, as the use case in https://github.com/hydrusnetwork/hydrus requires fast image checking and response.

**Comment by magwyz** [comment]
I currently have no interest having this feature in the main Pastec.
Please fork the project if you want / need to.
