### ISSUE TITLE
Feature: VisualWordsORB, but for Danbooru

### ISSUE THREAD

**Issue by DonaldTsang** [magwyz/pastec#69]
See https://www.gwern.net/Danbooru2017 for the dataset that is catered to Anime and cartoons
(Since on the website it is said that the original Passtec is for covers, art and labels, and not ACG)

**Comment by gwern** [comment]
Minor comment: if you just want to search anime images, there is already a reverse-image search available for Danbooru & other boorus: https://iqdb.org/

**Comment by DonaldTsang** [comment]
@gwern is IQDB's algorithm public? Because I can't seem to find it anywhere. Also does it use AKAZE/ORB/SURF as the algorithms? If not then pastec would function differently from IQDB.

**Comment by gwern** [comment]
No idea about what it uses or how the codebase is licensed. piespy has been helpful to me on other things, so I'm sure he'd answer if you you ask.

**Comment by DonaldTsang** [comment]
@gwern might be too early to call it a day, becuase Pastec uses ORB, which allows for partial image matching with cropping, scaling and rotation, as ORB uses local landmarks instead of global averages/differences like pHash does.
