### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by LowCapacity** [magwyz/pastec#71]
Hello!
Unfortunately I'm getting this error when querying the searcher:
Reranking 300 among 16955 images.
Segmentation fault (core dumped)

Any info on this if I'm doing something wrong? An older, closed issue mentioned duplicated images. I'm not sure if that's the case with the 17k images. Would this make pastec crash or is there something else?

edit: I tested with duplicate images but it seems pastec on the server is crashing regardless, even with 1 image.
It's weird because I had it running without any problems in a Windows10 Ubuntu VM and moved to a physical Ubuntu server.

Thanks and greetings!

**Comment by magwyz** [comment]
Did you check the opencv versions between your VM and your physical server?

**Comment by LowCapacity** [comment]
Thanks for the quick response!
I got it running, copying the executable from the VM to the server.
Something went wrong with compiling pastec on the physical server.
Do you happen to know which version of opencv is required? I have 3.2.0 on both ends.

**Comment by magwyz** [comment]
Sorry, no idea.
